# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\projects\hareg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\projects\hareg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\projects\hareg\CMakeFiles C:\projects\hareg\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\projects\hareg\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hareg

# Build rule for target.
hareg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 hareg
.PHONY : hareg

# fast build rule for target.
hareg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/build
.PHONY : hareg/fast

bin/bin.obj: bin/bin.cc.obj
.PHONY : bin/bin.obj

# target to build an object file
bin/bin.cc.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/bin/bin.cc.obj
.PHONY : bin/bin.cc.obj

bin/bin.i: bin/bin.cc.i
.PHONY : bin/bin.i

# target to preprocess a source file
bin/bin.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/bin/bin.cc.i
.PHONY : bin/bin.cc.i

bin/bin.s: bin/bin.cc.s
.PHONY : bin/bin.s

# target to generate assembly for a file
bin/bin.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/bin/bin.cc.s
.PHONY : bin/bin.cc.s

common/hareg_error.obj: common/hareg_error.cc.obj
.PHONY : common/hareg_error.obj

# target to build an object file
common/hareg_error.cc.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/common/hareg_error.cc.obj
.PHONY : common/hareg_error.cc.obj

common/hareg_error.i: common/hareg_error.cc.i
.PHONY : common/hareg_error.i

# target to preprocess a source file
common/hareg_error.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/common/hareg_error.cc.i
.PHONY : common/hareg_error.cc.i

common/hareg_error.s: common/hareg_error.cc.s
.PHONY : common/hareg_error.s

# target to generate assembly for a file
common/hareg_error.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/common/hareg_error.cc.s
.PHONY : common/hareg_error.cc.s

compression/compression.obj: compression/compression.cc.obj
.PHONY : compression/compression.obj

# target to build an object file
compression/compression.cc.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/compression/compression.cc.obj
.PHONY : compression/compression.cc.obj

compression/compression.i: compression/compression.cc.i
.PHONY : compression/compression.i

# target to preprocess a source file
compression/compression.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/compression/compression.cc.i
.PHONY : compression/compression.cc.i

compression/compression.s: compression/compression.cc.s
.PHONY : compression/compression.s

# target to generate assembly for a file
compression/compression.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/compression/compression.cc.s
.PHONY : compression/compression.cc.s

file/file.obj: file/file.cc.obj
.PHONY : file/file.obj

# target to build an object file
file/file.cc.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/file/file.cc.obj
.PHONY : file/file.cc.obj

file/file.i: file/file.cc.i
.PHONY : file/file.i

# target to preprocess a source file
file/file.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/file/file.cc.i
.PHONY : file/file.cc.i

file/file.s: file/file.cc.s
.PHONY : file/file.s

# target to generate assembly for a file
file/file.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/file/file.cc.s
.PHONY : file/file.cc.s

huffman/huffman.obj: huffman/huffman.cc.obj
.PHONY : huffman/huffman.obj

# target to build an object file
huffman/huffman.cc.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/huffman/huffman.cc.obj
.PHONY : huffman/huffman.cc.obj

huffman/huffman.i: huffman/huffman.cc.i
.PHONY : huffman/huffman.i

# target to preprocess a source file
huffman/huffman.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/huffman/huffman.cc.i
.PHONY : huffman/huffman.cc.i

huffman/huffman.s: huffman/huffman.cc.s
.PHONY : huffman/huffman.s

# target to generate assembly for a file
huffman/huffman.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/huffman/huffman.cc.s
.PHONY : huffman/huffman.cc.s

huffman/huffman_tree_node.obj: huffman/huffman_tree_node.cc.obj
.PHONY : huffman/huffman_tree_node.obj

# target to build an object file
huffman/huffman_tree_node.cc.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/huffman/huffman_tree_node.cc.obj
.PHONY : huffman/huffman_tree_node.cc.obj

huffman/huffman_tree_node.i: huffman/huffman_tree_node.cc.i
.PHONY : huffman/huffman_tree_node.i

# target to preprocess a source file
huffman/huffman_tree_node.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/huffman/huffman_tree_node.cc.i
.PHONY : huffman/huffman_tree_node.cc.i

huffman/huffman_tree_node.s: huffman/huffman_tree_node.cc.s
.PHONY : huffman/huffman_tree_node.s

# target to generate assembly for a file
huffman/huffman_tree_node.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/huffman/huffman_tree_node.cc.s
.PHONY : huffman/huffman_tree_node.cc.s

lzss/linked_list_matcher.obj: lzss/linked_list_matcher.cc.obj
.PHONY : lzss/linked_list_matcher.obj

# target to build an object file
lzss/linked_list_matcher.cc.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/lzss/linked_list_matcher.cc.obj
.PHONY : lzss/linked_list_matcher.cc.obj

lzss/linked_list_matcher.i: lzss/linked_list_matcher.cc.i
.PHONY : lzss/linked_list_matcher.i

# target to preprocess a source file
lzss/linked_list_matcher.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/lzss/linked_list_matcher.cc.i
.PHONY : lzss/linked_list_matcher.cc.i

lzss/linked_list_matcher.s: lzss/linked_list_matcher.cc.s
.PHONY : lzss/linked_list_matcher.s

# target to generate assembly for a file
lzss/linked_list_matcher.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/lzss/linked_list_matcher.cc.s
.PHONY : lzss/linked_list_matcher.cc.s

lzss/lzss.obj: lzss/lzss.cc.obj
.PHONY : lzss/lzss.obj

# target to build an object file
lzss/lzss.cc.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/lzss/lzss.cc.obj
.PHONY : lzss/lzss.cc.obj

lzss/lzss.i: lzss/lzss.cc.i
.PHONY : lzss/lzss.i

# target to preprocess a source file
lzss/lzss.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/lzss/lzss.cc.i
.PHONY : lzss/lzss.cc.i

lzss/lzss.s: lzss/lzss.cc.s
.PHONY : lzss/lzss.s

# target to generate assembly for a file
lzss/lzss.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/lzss/lzss.cc.s
.PHONY : lzss/lzss.cc.s

main.obj: main.cc.obj
.PHONY : main.obj

# target to build an object file
main.cc.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/main.cc.obj
.PHONY : main.cc.obj

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hareg.dir\build.make CMakeFiles/hareg.dir/main.cc.s
.PHONY : main.cc.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... hareg
	@echo ... bin/bin.obj
	@echo ... bin/bin.i
	@echo ... bin/bin.s
	@echo ... common/hareg_error.obj
	@echo ... common/hareg_error.i
	@echo ... common/hareg_error.s
	@echo ... compression/compression.obj
	@echo ... compression/compression.i
	@echo ... compression/compression.s
	@echo ... file/file.obj
	@echo ... file/file.i
	@echo ... file/file.s
	@echo ... huffman/huffman.obj
	@echo ... huffman/huffman.i
	@echo ... huffman/huffman.s
	@echo ... huffman/huffman_tree_node.obj
	@echo ... huffman/huffman_tree_node.i
	@echo ... huffman/huffman_tree_node.s
	@echo ... lzss/linked_list_matcher.obj
	@echo ... lzss/linked_list_matcher.i
	@echo ... lzss/linked_list_matcher.s
	@echo ... lzss/lzss.obj
	@echo ... lzss/lzss.i
	@echo ... lzss/lzss.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

